-- MySQL Script generated by MySQL Workbench
-- Fri May 28 13:44:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`orador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orador` (
  `idOrador` INT NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idOrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`batizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`batizado` (
  `idBatizado` INT NOT NULL AUTO_INCREMENT,
  `Orador_idOrador` INT NOT NULL,
  `horaInicio` TIME NULL DEFAULT NULL,
  `horaFim` TIME NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_nome` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBatizado`),
  INDEX `fk_Batizado_Orador_idx` (`Orador_idOrador` ASC) VISIBLE,
  CONSTRAINT `fk_Batizado_Orador`
    FOREIGN KEY (`Orador_idOrador`)
    REFERENCES `mydb`.`orador` (`idOrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`boda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`boda` (
  `idBoda` INT NOT NULL AUTO_INCREMENT,
  `Orador_idOrador` INT NOT NULL,
  `horaInicio` TIME NULL DEFAULT NULL,
  `horaFim` TIME NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_nome` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBoda`),
  INDEX `fk_Boda_Orador1_idx` (`Orador_idOrador` ASC) VISIBLE,
  CONSTRAINT `fk_Boda_Orador1`
    FOREIGN KEY (`Orador_idOrador`)
    REFERENCES `mydb`.`orador` (`idOrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`casamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`casamento` (
  `idCasamento` INT NOT NULL AUTO_INCREMENT,
  `Orador_idOrador` INT NOT NULL,
  `horaInicio` TIME NULL DEFAULT NULL,
  `horaFim` TIME NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_nome` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCasamento`),
  INDEX `fk_Casamento_Orador1_idx` (`Orador_idOrador` ASC) VISIBLE,
  CONSTRAINT `fk_Casamento_Orador1`
    FOREIGN KEY (`Orador_idOrador`)
    REFERENCES `mydb`.`orador` (`idOrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`confissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`confissoes` (
  `idConfissoes` INT NOT NULL AUTO_INCREMENT,
  `Orador_idOrador` INT NOT NULL,
  `horaInicio` TIME NULL DEFAULT NULL,
  `horaFim` TIME NULL DEFAULT NULL,
  `Orador_nome` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idConfissoes`),
  INDEX `fk_Confissoes_Orador1_idx` (`Orador_idOrador` ASC) VISIBLE,
  CONSTRAINT `fk_Confissoes_Orador1`
    FOREIGN KEY (`Orador_idOrador`)
    REFERENCES `mydb`.`orador` (`idOrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `Orador_idOrador` INT NOT NULL,
  `horaInicio` TIME NULL DEFAULT NULL,
  `horaFim` TIME NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_nome` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Orador1_idx` (`Orador_idOrador` ASC) VISIBLE,
  CONSTRAINT `fk_Evento_Orador1`
    FOREIGN KEY (`Orador_idOrador`)
    REFERENCES `mydb`.`orador` (`idOrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`missa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missa` (
  `idMissa` INT NOT NULL AUTO_INCREMENT,
  `Orador_idOrador` INT NULL DEFAULT NULL,
  `Orador_nome` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_cargo` VARCHAR(45) NULL DEFAULT NULL,
  `horaInicio` TIME NULL DEFAULT NULL,
  `horaFim` TIME NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `dia` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idMissa`),
  INDEX `fk_Missas_OradorNome_idx` (`Orador_nome` ASC) VISIBLE,
  INDEX `fk_Missa_Orador1_idx` (`Orador_idOrador` ASC, `Orador_nome` ASC, `Orador_cargo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`noticia` (
  `idNoticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idNoticia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`viasacra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viasacra` (
  `idViaSacra` INT NOT NULL AUTO_INCREMENT,
  `Orador_idOrador` INT NOT NULL,
  `horaInicio` TIME NULL DEFAULT NULL,
  `horaFim` TIME NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_nome` VARCHAR(45) NULL DEFAULT NULL,
  `Orador_cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idViaSacra`),
  INDEX `fk_ViaSacra_Orador1_idx` (`Orador_idOrador` ASC) VISIBLE,
  CONSTRAINT `fk_ViaSacra_Orador1`
    FOREIGN KEY (`Orador_idOrador`)
    REFERENCES `mydb`.`orador` (`idOrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
